version: '2'
services:
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
  test:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mongo
    command: bash -c "/src/test-script.sh"
    environment:
      - MONGO_PORT=27017
      - MONGO_HOST=mongo
      - MONGO_DB=demo